version: '3.8'

services:
  mysqldb:
    image : mysql:5.7
    restart: always
    env_file: /.env
    environment:
      - MYSQL_ROOT_PASSWORD=merty37
      - MYSQL_DATABASE=mert
    ports:
      - "3306:3306"
    volumes:
       - /var/lib/docker/volumes

  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - '8080:8080'
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://localhost:3306/mert?useSSL=false&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "merty37",
        "spring.spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",
        "spring.jpa.hibernate.ddl-auto" : "create-drop"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true